### ISSUE TITLE
Inconsistent netgraph item location on runs

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_gui#150]
For example: on different runs of the spa.py model, the cortical netgraph item will sometimes appear on top of the other items and somtimes below.

**Comment by tcstewar** [comment]
This is actually an inconsistency in the autolayout system.  It doesn't guarantee a consistent order.  This could probably be fixed by careful use of OrderedDict in that system.

**Comment by tcstewar** [comment]
This has been fixed, thanks to #853
