### ISSUE TITLE
Quick way to stop moving sliders

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_gui#214]
Currently the only way to stop a moving slider is to right click and set value.

It is very hard to grab and take control otherwise.

Should we put a quick 'take control' option/button in?

**Comment by tcstewar** [comment]
Why not do it the same way as in old nengo?  

In nengo 1.4, just clicking anywhere in the slider stopped it from moving.  So if you miss the moving slider, it'll stop for you.

**Comment by cchan987** [comment]
that sounds good to me, we'll have to make sure to distinguish clicking inside from click-hold and dragging the slider component around.

**Comment by tcstewar** [comment]
> we'll have to make sure to distinguish clicking inside from click-hold and dragging the slider component around.

Just to be clear, that's not the behaviour in nengo 1.4.  In Nengo 1.4, clicking an dragging near the line of the slider (but not on the handle itself) is not treated as moving the whole component.  So clicking and dragging near the slider line was for controlling the position of the slider, but dragging inside the Componnet but farther away from the slider line was treated as moving the component.

I think the 1.4 behaviour is the right one to go with, as it means that if you slightly miss the slider handle, you don't end up changing the position of the component.

**Comment by cchan987** [comment]
Do we have an example model with moving sliders by chance?

**Comment by tcstewar** [comment]
> Do we have an example model with moving sliders by chance?

This should do it:
```python
import numpy as np
import nengo
model = nengo.Network()
with model:
    nengo.Node(np.sin)
```
