### ISSUE TITLE
Resetting value on slider menu option could also reset the slider range

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_gui#216]
When the slider range is set to a range differing from the original (ex. a range of -1 to 10), the slider no longer moves from top to bottom, rather it moves over a small fraction of the slider (when the function was originally doing a sin wave from -1 to 1.).

**Comment by tcstewar** [comment]
I don't understand what you mean here.  That sounds like the correct behaviour to me.

**Comment by celiasmith** [comment]
I agree, that sounds like what should happen.

**Comment by tcstewar** [comment]
Consensus at the dev meeting was that this is still desired behaviour, so I'm closing this.
