### ISSUE TITLE
Server shutdown confirmation with Ctrl+C fails on Windows

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#239]
![exc](https://cloud.githubusercontent.com/assets/850157/7900435/a3551dfe-0725-11e5-977c-499d5720e9e6.png)

**Comment by hunse** [comment]
Hmm, maybe we should see what IPython does for Windows? I used the same method as them for the shutdown confirmation.

**Comment by jgosmann** [comment]
They don't use that method on windows (they don't even register the signal handler).

**Comment by jgosmann** [comment]
On Windows the IPython notebook server gets shut down immediately when pressing Ctrl+C (though the console windows seems to have to loose focus first?).

**Comment by tcstewar** [comment]
This works for me now on my Windows.  Anyone else reporting this?  There's been a lot of changes to the server since this issue was reported....

**Comment by jgosmann** [comment]
n=1, good enough for me ^^

If anyone encounters problems with this, reopen the issue.
