### ISSUE TITLE
Help user make pretty netgraphs

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#249]
If you start dragging and resizing things (or do it by accident), it's hard to get a nice looking netgraph where all components are pretty much the same (unless you auto layout, which is nice, but moves things around).  We could:
- have a menu item on components to return to a 'default size'.  This could be network size dependent (like what auto layout does).
- have a menu item that makes things equal aspect ratio (?)
- have a menu item to turn on a snap to grid (this is included in interact.js)
- have a multi-select, align to top/middle/bottom crazy over the top solution... probably not worth the effort

**Comment by tbekolay** [comment]
Moved the non-overlapping suggestions to #857.
