### ISSUE TITLE
Axis values not showing up on value plots properly

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_gui#261]
Depending on what you set your range to, the numbers along the plot's vertical axis won't show up. For example, if you set the range on a value plot to "-2,2" these numbers will show up, but if you set it to "-3,3" then no numbers on the ends will show up.

**Comment by cchan987** [comment]
I'm thinking that we should have the y-axis labels at the max and min range boundaries as well as the halfway point between the two. If the halfway point is a decimal (ie. the range is from 0 - 5 so midpoint is 2.5) we would fix that to a single decimal place. Any opinions on this?

**Comment by tcstewar** [comment]
> Any opinions on this?

I wouldn't have the midpoint at all.  All we need is the min and max.
