### ISSUE TITLE
Rename project to nengo_gui

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_gui#266]

**Comment by cchan987** [comment]
This would require changing all references in the code from VIZ to GUI (or something like that). Should this be done after all the milestone issues are closed since they're will likely be a large number of conflicts otherwise?

**Comment by tcstewar** [comment]
> This would require changing all references in the code from VIZ to GUI (or something like that). Should this be done after all the milestone issues are closed since they're will likely be a large number of conflicts otherwise?

Yes.  This will be done on friday, I think....

**Comment by tbekolay** [comment]
Thursday ;)

**Comment by tbekolay** [comment]
Quick discussion: what should we do with what is currently nengo_gui? I don't want to flat out delete the repository since that will delete all of the discussion in issues and pull requests. So I think we need to rename it to something else.

Possibilities:

1. `nengo_gui_old`
2. `nengo_gui_experiment`
3. `obsolete_nengo_gui`
4. `nengo_gui_dont_use_this_one`

Feel free to propose additional ones.

Then, I think we should probably move this from the Nengo org to the ctn-waterloo org. Just because people will got to https://github.com/nengo and will expect that the projects there are current ones. Make sense? Or, we could move it to https://github.com/ctn-archive/

**Comment by tbekolay** [comment]
I think my votes are to 5 and 2 (rename to `nengo_gui_2014` and move to `ctn-archive`).

**Comment by celiasmith** [comment]
+1

Trevor Bekolay wrote:

**Comment by jgosmann** [comment]
7. `nengo_gui_alpha`
8. `nengo_gui_prototype`

I'm fine with with 5 and 2.

**Comment by s72sue** [comment]
I think its nice to have the year in there, so nengo_gui_2014 sounds good.

**Comment by tbekolay** [comment]
Cool, @tcstewar is cool with this too, so I'll do all that.

**Comment by tbekolay** [comment]
The former Nengo GUI is now resting comfortable in its [new home](https://github.com/ctn-archive/nengo_gui_2014).

**Comment by jgosmann** [comment]
To what should `IPythonViz` be renamed? `IPythonGUI`?

**Comment by celiasmith** [comment]
yup :+1:

**Comment by tbekolay** [comment]
Yes, I think so. Actually, it's worth writing out what I'll do now since the only thing left is the code editor. Here's the plan; LMK if anything seems wrong:

- [ ] Rename repository from `nengo_viz` to `nengo_gui`
- [ ] Rename `nengo_viz` directory to `nengo_gui`
- [ ] grep for `nengo_viz` and change to `nengo_gui`
- [ ] grep for `viz` and change to `gui` in Python scripts
- [ ] `viz.py` -> `core.py` ? `gui.py` ?
- [ ] For the objects, `Viz` -> `GUI`? `VizSim` -> `GUISim`?
- [ ] For JS, rename `VIZ` namespace to `Nengo`
- [ ] Rename all files starting with `viz_` to remove the `viz_`
- [ ] `viz.js` -> `nengo.js`

I think that's the bulk of it. If anything in there sounds wrong, LMK.

**Comment by tbekolay** [comment]
FYI this is all happening now! If you have any existing branches, they're going to need to essentially be rewritten, as all these things above are changing. Good luck!

**Comment by tbekolay** [comment]
Also, you should update your remotes because this will be renamed.

**Comment by jgosmann** [comment]
Github seems to handle the old remotes still well, but updating is better.

**Comment by tbekolay** [comment]
OK, this is almost done. I kept the Python names as they are for now; we can change them later...

**Comment by Seanny123** [comment]
Resolved in #460 a really long time ago
