### ISSUE TITLE
Don't allow spike plots for ensembles running in Direct mode

### ISSUE THREAD

**Issue by s72sue** [nengo/nengo_gui#293]
Refer #292, #145 

Remove the temporary fix on the server side and make the fix on the client side (this would require passing the information regarding the neuron type of an ensemble to the client).

The spike plot option should not show up for the ensembles in direct mode

**Comment by Seanny123** [comment]
Closing because this was fixed a while ago. BTW, you can close issues automatically by mentoining them in the last line of your pull request as seen [here](https://github.com/blog/1506-closing-issues-via-pull-requests).
