### ISSUE TITLE
Fix LICENSE.md

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#296]
There's a bunch of stuff in there that's just wrong, since it was cut-and-paste from nengo_gui

**Comment by tbekolay** [comment]
Technically this will be nengo_gui soon ;) But yeah, we should make sure all these files are correct before pushing to PyPI.

**Comment by tcstewar** [comment]
Fixed by f5c9e7ba5c0e46445e7798241ccae3b132a43198
