### ISSUE TITLE
Zooming on mac causes overlaps

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#308]
To see this problem, place a graph underneath an ensemble so the y-axis is almost touching.  If you then zoom in, it will touch.  Same with side/x-axis.  This seems to be mac specific and is on firefox and chrome.

**Comment by jgosmann** [comment]
I think something broke the zooming of plots in general.

**Comment by jgosmann** [comment]
Yes, the zooming is definitely broken compared to earlier versions.

**Comment by jgosmann** [comment]
28fdabf657172a1d6e3417b0e5b27cb35a75cf85 is the first bad commit

**Comment by jgosmann** [comment]
@tbekolay I think, this should go into the release or at least be fixed asap. Zooming feels super wrong right now because plots and the netgraph move relative to each other while zooming.

**Comment by tcstewar** [comment]
> I think, this should go into the release or at least be fixed asap. Zooming feels super wrong right now because plots and the netgraph move relative to each other while zooming.

100% agree

trying to find the fix now....

**Comment by jgosmann** [comment]
got it

**Comment by jgosmann** [comment]
Made a PR to fix the zooming behavior. At least the widely wrong behavior. There is still a small difference in the zooming of plots and netgraph, but it's not that bad and can be fixed later.

**Comment by jgosmann** [comment]
(and I think it's not worse than it used to be)

**Comment by tcstewar** [comment]
This is all fixed now, thanks to #321 and #310
