### ISSUE TITLE
Code editor does not capture all keys

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#311]
The code editor does not capture all key presses. This is most apparent for the space bar which plays and pauses the model instead of inserting a space. For me this behaviour is consistent across browsers and OSes. The editor is unusable in this state.

A minor issue is that undo key combinations not used by the editor have an effect on the network while the editor has focus (but other undo combinations are undoing typing in the editor). So this is not completely consistent, but usable (and probably won't be noticed by most users).

**Comment by jgosmann** [comment]
I'm not familiar with the editor code, so I probably won't fix it myself. But we might have to stop the propagation of the keydown event from the editor.

**Comment by jgosmann** [comment]
But we should do that only for printable keys and key combinations used by nengo_gui. Otherwise the browser's own keybindings might be disabled?

**Comment by tcstewar** [comment]
Here's my fix:  #312

**Comment by tbekolay** [comment]
Can we consider this fixed now?

**Comment by jgosmann** [comment]
More or less ... we might encounter similar problems in the future, but space bar works now.
