### ISSUE TITLE
Ctrl-e does not work if editor in focus

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#315]
You have to de-focus the editor to be able to use the shortcut to hide it.

**Comment by tcstewar** [comment]
I think this is fixed due to #312 now.  Is this still a problem for anyone?

**Comment by jgosmann** [comment]
Yes. Ctrl+e jumps to the end of the line in the editor.

**Comment by tcstewar** [comment]
> Yes. Ctrl+e jumps to the end of the line in the editor.

What browser?  It doesn't do that for me.

**Comment by jgosmann** [comment]
Chrome and Firefox

**Comment by tcstewar** [comment]
> Chrome and Firefox

Both Chrome and Firefox work fine for me under Windows...  :(

**Comment by bjkomer** [comment]
Chrome and Firefox are fine with Ubuntu for me

**Comment by jgosmann** [comment]
Might be an OS X issue then?

**Comment by jgosmann** [comment]
It might just be that Ctrl-E is a standard key combination in OS X input fields. Cmd-E works as it should. We probably should replace Ctrl with Cmd in the help window on OS X.

**Comment by tbekolay** [comment]
Ctrl-E is an emacs shortcut for go to the end of the line; all of Mac OS X's text boxes use emacs shortcuts when using ctrl (because most shortcuts non-nerds will use should be using Cmd).

We should definitely change Ctrl to Cmd (or rather ⌘) in the help window though.

**Comment by tbekolay** [comment]
Made #421 to track that issues specifically.
