### ISSUE TITLE
Minimap shows unnecessary whitespace at bottom

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#320]

**Comment by s72sue** [comment]
I'm not sure how hard it would be to enable the minimap to be moved, but
that would solve this problem.
I think it would be nice to be able to move the minimap on the screen since
sometimes it covers parts of the model.

**Comment by s72sue** [comment]
Also, this whitespace issue might not necessarily be related to minimap,
since there is exra whitespace on the entire screen. For example: if you
try to move an ensemble downwards, it gets hidden behind a white patch on
the screen.

**Comment by jgosmann** [comment]
To clarify: There is not too much whitespace around the minimap, but within the minimap itself.
![mmws](https://cloud.githubusercontent.com/assets/850157/7997679/e2dd5c5c-0afe-11e5-83c5-be348d398d4c.png)

The white bar is reported as issue #314 and a patch is proposed in #316.

**Comment by s72sue** [comment]
I see what you mean. Thanks for clarifying :)

**Comment by jgosmann** [comment]
I think, I fixed this some time ago. Will verify later.

**Comment by jgosmann** [comment]
23 days later: If it was fixed, it is broken again. :/

**Comment by jgosmann** [comment]
The viewbox isn't correctly calculated either ... :sob:

**Comment by jgosmann** [comment]
oh, it is calculated correctly
had still checked out an old commit :relieved: 
but the whitespace at the bottom is still an issue.
