### ISSUE TITLE
When a model is running fast, speed > 5x... Graphs can lag behind

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_gui#357]
Graphs do not plot their lines until the user pauses. It appears there is a lag of what is being plotted.
By increasing the complexity of the model, which causes the model to run slower, the graphs will update in real time.
Venturing a guess I would say that this is due to slow hardware.
A speed throttle would solve this issue

**Comment by tcstewar** [comment]
I'm relatively sure this is about the SimControl getting ahead of the Value Component.  The x-axis limits on the plots are based on whatever points in time the SimControl thinks the simulation is at, but it is possible for that to get ahead of what data points the Value component has access to.  So one solution might be to have the Value component notice if the data it's being asked to plot is outside the window of time that it has access to, and if so it shifts its time index back to whatever the most recent data is it has access to.
