### ISSUE TITLE
Nodes and direct mode xy-plots can be confusing

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_gui#363]
It's easy to see that an xy-plot is working for an ensemble, because the noisy representation moves a bit making the line visible. That's not the case with nodes and ensembles in direct mode; if the value is static, it looks like the xy-plot isn't even working. You can't even really see the blue dot where the value actually is.

I'm not sure the best resolution to this, though, because not being able to see it is, basically, correct. But perhaps for direct mode and node xy-plots, we can make the line thicker? Or, actually, maybe a better resolution is to keep the line the same size, but draw a big blue at the value at the current timestep (the line would just be trail or where the value was recently).

**Comment by tbekolay** [comment]
Then, I suppose the question would be, should that circle still be drawn on spiky ensembles?

**Comment by bjkomer** [comment]
We could have circle/line thickness a configurable option for those plots. It would default to the regular way for spiking ensembles, and default to a bigger dot for direct mode.

**Comment by tcstewar** [comment]
I like the idea of a larger dot at the end all the time (for spiky ensembles as well as Direct and LIFRate modes)...  one thing that'd do is help indicate what the most recent data is when it's paused (or a screen shot)

**Comment by tcstewar** [comment]
Closed by #646
