### ISSUE TITLE
Sliders do not reset when the model resets

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#365]
If I run a model, move some sliders, and then change the code and hit play again, the sliders stay at their old value.

**Comment by bjkomer** [comment]
+1 This behaviour is really confusing when debugging models. The sliders should either visually reset, or use their old values when the simulation is reset. I can see use cases for both behaviours, so it might be good to look into having this configurable, or have buttons for 'full reset' and 'soft reset'.
