### ISSUE TITLE
nengo_gui fails to display SPA networks and then crashes on reloading

### ISSUE THREAD

**Issue by mundya** [nengo/nengo_gui#367]
Running nengo_gui from master with `nengo_gui 4-convolution.py` (`4-convolution.py` is from `nengo_benchmarks`) the SPA networks aren't shown.

On pressing Reload the server crashes with this error:

```
(process:3351): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Traceback (most recent call last):
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/swi.py", line 237, in handle_ws_request
    getattr(self, command)(*[client] + args[1:], **db)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/server.py", line 147, in ws_viz_component
    component.update_client(client)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/components/netgraph.py", line 243, in update_client
    self.expand_network(network, client)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/components/netgraph.py", line 349, in expand_network
    self.create_object(client, net, type='net', parent=parent)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/components/netgraph.py", line 382, in create_object
    client.write(json.dumps(info))
  File "/usr/lib64/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_keys(['default']) is not JSON serializable
```

Python 3.4, Arch Linux, running from within a virtualenv, Firefox 38.0.5

This is the exact code I'm running:

```python
"""
Nengo Benchmark Model #4: Circular Convolution

Input: two random D-dimensional vectors
Output: the circular convolution of the inputs

"""

import nengo
import nengo.spa as spa

import logging
from matplotlib import pyplot as plt
logging.basicConfig(level=logging.DEBUG)

D = 16    # dimensionality
T = 0.5      # time to run the simulation for
SD = 16

model = spa.SPA()
with model:
    model.inA = spa.Buffer(D, subdimensions=SD)
    model.inB = spa.Buffer(D, subdimensions=SD)

    model.result = spa.Buffer(D, subdimensions=SD)

    model.cortical = spa.Cortical(spa.Actions('result = inA * inB'))

    model.input = spa.Input(inA='A', inB='B')

    probe = nengo.Probe(model.result.state.output, synapse=0.05)

    ideal = nengo.Node(model.get_output_vocab('inA').parse('A*B').v)
    probe_ideal = nengo.Probe(ideal)
```

**Comment by tbekolay** [comment]
Hmm... this script runs properly for me (albeit slowly) using Nengo master and v2.0.1. What version of Nengo are you using? I can't imagine what else it would be... I guess to start debugging I'd look at what's in `info` at at line 382 of `components/netgraph.py`. Put it in a try / except and do `import pdb; pdb.set_trace()` in the except and look at what's in `info`.

**Comment by xchoo** [comment]
Odd. I'm not getting this error.. (Not even a slowdown)

**Comment by tbekolay** [comment]
Well, it is an SPA network, it's going to be slow ;) On my laptop at least.

**Comment by mundya** [comment]
This seems to be a Python 3 error, it runs fine for me on Python 2.7

**Comment by tbekolay** [comment]
Oh dang, should have noticed the `python3.4` in the path. Will try to reproduce in 3.4.

**Comment by xchoo** [comment]
I think I've figured out the problem. In Python 2, dictionary keys are returned as list objects, but in Python 3, it's a view into the dictionary (the dictionary key list is being obtained in ```pointer.py```, line 84). JSON is able to serialize lists, but not views, so it crashes. 

Proposed fix would be ```list(obj.outputs.keys())```, but according to the interwebs, this is not thread safe. Do we need to worry about thread safety here?

**Comment by tbekolay** [comment]
Nah screw threads, just do `list(obj.outputs.keys())`.

**Comment by xchoo** [comment]
Looks like this problem will also occur anywhere we are trying to JSON serialize ```dict.values()``` or ```dict.items()``` as well.

**Comment by tbekolay** [comment]
Yeah; this is something that the automated `2to3` does.

**Comment by tbekolay** [comment]
This script now works for me in Python 3 (thanks to #370).
