### ISSUE TITLE
possible to run slow?

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo_gui#369]
a lot of the time things are happening really quickly and it would be nice to be able to slow down the model sim speed so i can adjust sliders at the millisecond level as it's going along.

**Comment by arvoelke** [comment]
Duplicate of #91, related to #357

I've wanted this as well. My temporary solution was to up' the number of neurons to slow it down.

**Comment by tbekolay** [comment]
There's also this [`time.sleep` workaround](https://github.com/ctn-waterloo/summerschool2015/wiki/Resources#nengo-tips).

**Comment by studywolf** [comment]
ah sorry, did a quick scan but didn't see it already
