### ISSUE TITLE
Cannot import file from same folder as script

### ISSUE THREAD

**Issue by hunse** [nengo/nengo_gui#379]
My script imports a helper file from the same folder. This doesn't work.

**Comment by tcstewar** [comment]
Does it work if you start nengo_gui from that folder?

**Comment by hunse** [comment]
Nope.

**Comment by tbekolay** [comment]
What if you start it from that folder, and you have an `__init__.py` file in that folder?

**Comment by hunse** [comment]
More deets:
- If I start nengo_gui from within the file, and run the file directly, it works fine. It's only if I start nengo_gui from the command line and then try to open the file that I have problems. This is probably because running the script does the imports right away (when it's still all normal Python, so nothing can go wrong), so then when nengo_gui re-execs the file, the module is already imported, so it doesn't have to worry about finding it.
- Adding the `__init__.py` file doesn't help.

**Comment by arvoelke** [comment]
What if you add

`sys.path.append(os.path.dirname(__file__))`

It's not the recommended solution but hopefully at least that should work for now?
