### ISSUE TITLE
Loading a file with errors is bad

### ISSUE THREAD

**Issue by hunse** [nengo/nengo_gui#380]
Loading a script with errors (syntax, etc.) in it no longer crashes the program, but there's still a number of problems. So far, I've noticed that:

1. The error gets suppressed silently. It's not printed to the console or anything, so there's no way (AFAIK) for the user to see what the error is.
2. We still try to load the config file, which results in a bunch of "error parsing config" messages printed to the console.

**Comment by hunse** [comment]
I looked into fixing this, but the difficulty is that there's no way to have a file loaded in the code window, such that we can display errors, etc., while having the rest of the program realize that the file is not properly loaded such that it should not go on with its normal routine (e.g. we don't want it loading or saving config files).

**Comment by Seanny123** [comment]
Resolved a while ago during a refactoring. Tested it today and it's still resolved.
