### ISSUE TITLE
Not clear that semantic pointers need to be all caps

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_gui#389]
We should have a validation step in the "Set Value..." modal for pointer plots that disallows values that are not in all caps. Right now, it allows you to try to set it to something like `my_pointer` which will silently do nothing.

**Comment by bjkomer** [comment]
Side note: it doesn't need to be all caps, just the first letter needs to be capitalized

**Comment by Seanny123** [comment]
Resolved a long time ago...
