### ISSUE TITLE
Convert spike charts to a single SVG path

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#394]
As pointed out by Roland, "you are drawing each line with its own SVG Line element.  It turns out that each SVG element causes (at least) 1 call from the CPU to the GPU, and this quickly becomes the perf bottleneck for many apps.  If you change the spike chart code to use a single SVG Path element to draw all of the lines in the chart (moveTo, LineTo, …), you will find a dramatic speedup when it is drawn.  This will give you a lot of the speedup you would experience by converting the chart to use WebGL.  In the future, if you want to be able to control the color, size, line type, etc. of each line, it would be a good time to check out WebGL."

**Comment by studywolf** [comment]
awesome tip!

**Comment by tbekolay** [comment]
Super awesome! It would be great to have speedy rasters :rainbow:

**Comment by tcstewar** [comment]
Done in #417
