### ISSUE TITLE
Main script name

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_gui#405]
I've heard a few people say "run nengo" when running `nengo_gui`. Perhaps the graphical UI script should just be called `nengo` rather than `nengo_gui`?

**Comment by celiasmith** [comment]
i'd be fine with that.

Trevor Bekolay wrote:

**Comment by tcstewar** [comment]
> Perhaps the graphical UI script should just be called nengo rather than nengo_gui?

Sounds good to me, too.

**Comment by Seanny123** [comment]
This would be consistent with the last version so +1 from me.

**Comment by Seanny123** [comment]
Resolved in the latest release.
