### ISSUE TITLE
Value Plot: Changing a population from Ensemble to EnsembleArray crashes the server

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo_gui#406]
If you have a value plot stored in the config file, and you change a population from and Ensemble to an EnsembleArray, it will crash the server. It happens because the value plot is looking for the ```size_out``` attribute of the ensemble to determine how many dimensions it should plot. 

However, an EnsembleArray is a network which does't have this property, and so the server crashes.

This problem will also occur if you have a value plot up for an ensemble, and convert that ensemble to a network (value plots are not valid for networks).

Adding logic in to check the population type when loading up a config file, and disabling plots that are not longer valid should fix this issue.

**Comment by bjkomer** [comment]
I think this is related to #398

**Comment by tbekolay** [comment]
Fixed in #416.
