### ISSUE TITLE
Refresh Simulator when Sourced file updates

### ISSUE THREAD

**Issue by wchapman** [nengo/nengo_gui#407]
Currently if you have:
=== Main.py ===
from myFile.py import myClass

Whenever you edit main.py, nengo_gui will restart the simulation, taking the change in to account. However, if you edit myFile.py, the gui does not restart the simulation.

**Comment by tbekolay** [comment]
This would be super convenient! One difficulty I can see will be differentiating between imports that the user has made and therefore should watch and imports that the user hasn't made and we probably shouldn't watch (e.g., `numpy`. But maybe not `nengo`?)

One way we could achieve this is to explicitly tell `nengo_gui` about files we want to watch (that way, we can have it be either an imported script defining part of the model, or a file in `nengo` that we're tweaking and want to see the effects). A few ways of doing this:

1. Magic variable. Something like `nengo_gui_watches = ['myfile.py']` or `nengo_gui.watches = ['myfile.py']`.
2. Function exposed by `nengo_gui`. `nengo_gui.watch('myfile.py')`.

**Comment by jgosmann** [comment]
Might be worth to take a look at the [IPython autoimport functionality](https://ipython.org/ipython-doc/dev/config/extensions/autoreload.html).

**Comment by tcstewar** [comment]
Hmmm...  I do like the idea of the ```autoreload``` sort of thing.  That'd be quite handy!

That said, it might be easier to just encourage people to use ```reload``` if they need to.  So this should solve @wchapman 's orginal problem:

```python
import myFile
reload(myFile)
from myFile.py import myClass
```

**Comment by wchapman** [comment]
@tcstewar , the `reload()` function seems to work within the nengo_gui.
Thanks for the tip, everyone!
