### ISSUE TITLE
Associative Memory does not show Semantic Pointer

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#413]
When trying to visualize the output of an Associative Memory module, there's no option to display a semantic pointer, you can only display values. An obvious work-around is to append a buffer, but this is a bit annoying.

**Comment by xchoo** [comment]
This works on my machine (nengo 2.0.1, nengo_gui 0.1.3). Can someone else confirm this?

**Comment by Seanny123** [comment]
It works now, so closing...
