### ISSUE TITLE
Make it easier to give nodes a semantic pointer value

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#414]
When developing and debugging a SPA network it's nice to have some default values being input every time you run your simulation. This can be done with either `spa.Inputs` or `nengo.Node` however there are disadvantages to either of these approaches.

- `spa.Inputs` has to be connected with `spa.CorticalActions` which is a bit unfriendly
- `nengo.Node` can't parse SPA vocab values if you want to set it to a new value

Which one of these approaches should be made friendlier?

**Comment by tcstewar** [comment]
Hmm, ```spa.Inputs``` is supposed to be like this, and shouldn't require a ```CorticalActions```.  Here's how I use it:

```python
    model.value = spa.Buffer(dimensions=32)
    
    def my_input(t):
        if t < 0.1:
            return 'CAT'
        elif 0.1 < t < 0.2:
            return 'DOG'
        else:
            return '0'
    model.input = spa.Input(value=my_input)
```

**Comment by Seanny123** [comment]
So after re-reading the documentation, this actually makes sense, however because there were no buffers in the documentation example, my brain couldn't parse it. I'll correct the documentation.

**Comment by Seanny123** [comment]
Resolved by the improved Tutorial documentation as provided by @tcstewar
