### ISSUE TITLE
Making a slider for a passthrough node gives `NaN`

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_gui#423]
If you make a slider from a passthrough node, the slider pops up with the value `NaN`. In a sense, this is correct, but in another sense, pressing play will crash the simulation with `FloatingPointError: invalid value encountered in less` while doing `LIF.step_math`.

Possible solutions:

1. Don't allow sliders for passthrough nodes (this would be a bummer).
2. Pop them up in some kind of disabled state; update them once the simulation starts.
3. Default to 0. Update once the simulation starts.

**Comment by Seanny123** [comment]
I would prefer option 3, but I'm not totally clear why initialising to NaN is a technically correct in the first place?

**Comment by tbekolay** [comment]
Because a passthrough node has output of `None` because its output is not defined until it has some input. `None` is not a number, but Javascript doesn't have a `None`, so it would be `null`, `undefined`, or `NaN`, they're all kind of correct.

**Comment by Seanny123** [comment]
In that case, I find option 2 to be more intuitive. Shall I implement it or
should this be discussed further?

**Comment by tcstewar** [comment]
> In that case, I find option 2 to be more intuitive. Shall I implement it or
> should this be discussed further?

I'd still stick with option 3, as it's *much* simpler, and this aspect about ```None``` is a fairly esoteric implementation detail, so I'd argue that ```0``` is more intuitive than some sort of weird disabling thing that isn't present in any other case.

**Comment by Seanny123** [comment]
I've changed my mind and now agree with the simplicity presented by option
2.

**Comment by tcstewar** [comment]
> I've changed my mind and now agree with the simplicity presented by option
> 2.

Do you mean 3?  3 seems simpler than 2 to me....

**Comment by Seanny123** [comment]
Yeah, I totally meant 3. Gosh darn number dyslexia.

**Comment by tcstewar** [comment]
Fixed by #658
