### ISSUE TITLE
Update sliders when the dimensionality of a Node changes

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_gui#425]
It would be nice if the sliders automatically updated to reflect the dimensionality of the Node they are controlling. Currently, if you create a 1D node, make a slider for it, and then change it to a 2D node, there is still only one thing to slide on the gui. This still runs fine, but you can only control one of the dimensions. In the reverse case with 2 sliders for a 1D Node, it also still runs fine but the second slider does nothing. Deleting and adding the slider fixes it, but it would be more convenient if this happened automatically.

**Comment by tcstewar** [comment]
This should be happening now, thanks to #514
