### ISSUE TITLE
Better notification about exception during build

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#434]
I am getting an exception during the build process from nengo_spinnaker which is only displayed in the terminal and the gear symbol keeps spinning.

**Comment by celiasmith** [comment]
This might be less of an issue with the console implemented (as long as it would pop that up)?

**Comment by tcstewar** [comment]
At the moment only errors before the build step are shown in the console, but it should be straightforward to send other errors there as well.

**Comment by jgosmann** [comment]
> This might be less of an issue with the console implemented (as long as it would pop that up)?

Yes.

But it seems that the exception also breaks nengo_gui and I have to restart it.

**Comment by tcstewar** [comment]
This should be fixed by #483
