### ISSUE TITLE
(For some backends) perform filtering by setting the connection synapse

### ISSUE THREAD

**Issue by mundya** [nengo/nengo_gui#437]
At the moment (I believe) that all filtering of plotted values is done by the client. For some backends (i.e., SpiNNaker) this results in the plots being incredibly noisy, to fix this filtering should be applied by the backend.

**Comment by tcstewar** [comment]
There's now a prefiltered_output branch that makes this change for value plots.  Can you check if that helps for SpiNNaker?

I'm tempted to do this on all backends...  the only problem is that it means you can't change that filter on the fly (while a model is running), but that's not even a feature we support at the moment.

**Comment by mundya** [comment]
Because I'm a scientist I decided to test this at the same time as a neater neural model, but yes `prefiltered_output` makes for a huge improvement for me.

**Comment by tcstewar** [comment]
Done in #461

**Comment by mundya** [comment]
Yay!
