### ISSUE TITLE
Not able to set value graph range to have a negative maximum value

### ISSUE THREAD

**Issue by fewtrem** [nengo/nengo_gui#441]
If I try to set the maximum of a graph to a negative value e.g. range -1 to -0.5 it is not possible as the gui thinks it is not in the correct format

e.g. typing "-1.0,-0.5" into the range setting box

**Comment by teslar** [comment]
I tried that on a slider and it's the same there.

Even more funkily, it will accept "-0.5, -1", but the resulting slider cannot be moved: -1 appears as the top of the slider range, with the slider at that point, but it can not actually be moved down

**Comment by cchan987** [comment]
It seems that whenever the second (max) value for the range is negative, the modal reports that it is invalid.

**Comment by cchan987** [comment]
There is very odd behaviour now:
set range: -3,-1 (everything is ok)
set range: -2,-1 (the y axis labels show 2.0 at the origin to 1.0 at the top, this should be -2 at the origin to -1 at the top...)

**Comment by cchan987** [comment]
I believe that this issue is resolved and the remaining problem lies in #450.
Hence this should be closed.
