### ISSUE TITLE
Y axis labels get cut off if they're too long

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#450]
If you sent the scale on a value plot to be 0 to 1000 (or -1,-.1), the margin cuts off some of the text.  Here's a purported solution to this kind of problem that @tcstewar found:

http://stackoverflow.com/questions/21603800/how-to-fit-variable-length-tick-labels-on-a-d3-line-chart

**Comment by cchan987** [comment]
closed by #502
