### ISSUE TITLE
Show Semantic Pointer output off of Circular Convolution network

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#452]
This way, I don't need to add a buffer between the circular convolution network and another network to see the semantic pointers being represented.

**Comment by Seanny123** [comment]
I'm going to enable the plot IFF the circular convolution network inputs share the same vocabulary.

**Comment by tcstewar** [comment]
> I'm going to enable the plot IFF the circular convolution network inputs share the same vocabulary.

Why?  I'm not quite following the logic there....  also, how will you know what the vocabularies are?

**Comment by Seanny123** [comment]
I was going to do it only if the inputs shared the same vocabularies, because I assumed this would be the only place it would be same to assume an output vocabulary.

Admittedly, I haven't figured how to get the input vocabularies... Is there a better way to do this? Should I not be trying to do this in the first place?

@xchoo seems to think making a spa.Binding() module would be a better idea.

**Comment by tcstewar** [comment]
> Admittedly, I haven't figured how to get the input vocabularies..

One of the major points of the ```spa.*``` modules is to associate inputs and outputs with vocabularies.  Without that, there's no way of finding out what vocabulary is used for inputs or outputs.  So I think @xchoo is right -- if you want a circular convolution network that's associated with a vocabulary, then just making a quick ```spa.Binding``` module would make sense.
