### ISSUE TITLE
Resetting the simulation while it is running leaves the gear spinning at the bottom

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_gui#467]
If you press the reset button without stopping the simulation first, the simulation will be stopped and reset correctly, but instead of a play button on the bottom right, there will be a spinning gear. You now need to click that gear to turn it into the arrow and click it again to play. It should just be an arrow right away.

**Comment by cchan987** [comment]
The sim control time also does not reset

**Comment by cchan987** [comment]
The time that is displayed in textual format in the bottom left is not reset either.
