### ISSUE TITLE
More subtle indication that nengo_gui isn't running

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#492]
As discussed in #480 (after it had been merged), the bright red indication that nengo_gui has stopped running is perhaps a bit much.   I've suggested just not changing the background, but @jgosmann pointed out that if you do happen to close the modal then there's no indication that it has stopped.

Three options come to mind:

 - a more subtle color change
 - disable closing the modal
 - do something like what Jupyter does: ![snapshot2](https://cloud.githubusercontent.com/assets/850157/8736600/f72eff76-2be7-11e5-9a91-50a447956bce.png)

Thoughts/suggestions?

**Comment by cchan987** [comment]
Personally I feel that something aggressive and obtrusive is right on point for something like this. 
It would worry me that if we had a (not connected) icon in the corner/tool-bar it could potentially go unnoticed and perhaps the user would lose work because they had no idea of being disconnected.

**Comment by cchan987** [comment]
After discussion, a less harsh red seems the way to go. Any color suggestions?

**Comment by tcstewar** [comment]
I think the modal is using #a94442
