### ISSUE TITLE
Nengo GUI visual bug

### ISSUE THREAD

**Issue by pabogdan** [nengo/nengo_gui#499]
Screenshot 1

Starting nengo gui this morning I get this weird visual bug. The code is inconsequential, I've tried with empty files and simpler examples as well. The browser used is Chrome and the setup has remained the same for weeks now. This first image shows the problem: no simulation bar at the bottom.
![Screenshot 1](http://i.imgur.com/08gdgFb.png)

Screenshot 2

In my attempt to understand what was happening I tried zooming in and out, which didn't have the desired effect. Instead, scrolling down revealed the missing bar, but with missing timeline and simulation start button.
![Screenshot 2](http://i.imgur.com/mfMp19U.png)

Screenshot 3

Workaround 1: Putting the browser in fullscreen mode
![Screenshot 3](http://i.imgur.com/tom0EaK.png)

Screenshot 4

Workaround 2: Closing the text editor
![Screenshot 4](http://i.imgur.com/bDVnzpJ.png)

I want to just point out that simulations still run, you just can't select the amount of simulation time you want to see and you have to start / pause it by pressing space.

**Comment by pabogdan** [comment]
Have just tried it in Firefox and everything works as expected. Must be an issue with the latest Chrome update.

**Comment by tcstewar** [comment]
> Have just tried it in Firefox and everything works as expected. Must be an issue with the latest Chrome update.

Argh...  yup, I just confirmed this on a Windows 8.1 machine and on a Linux Mint machine...  The problem occurs with Chrome 44.  Although on Mint going to fullscreen doesn't work as a workaround.

Thank you for finding this!  We'll sort out what the problem is -- at least it's very replicable!

**Comment by tcstewar** [comment]
Looks like this is a bug in Chrome that is breaking a lot of websites for people:

http://code.google.com/p/chromium/issues/detail?id=506893

**Comment by tcstewar** [comment]
I think I've got a fix for it...  if you could try out the ```fix-editor-scrolling``` branch and see if that works for you, that'd be great!

**Comment by pabogdan** [comment]
Yes, it does seem to fix it. Good job!
