### ISSUE TITLE
Code folder re-organisation

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#500]
The layout of the JavaScript `static` code folders is a bit awkward. Would people be open to dividing it into `netgraph_components`, `panel_components` and leaving the core stuff at the root folder?

**Comment by cchan987** [comment]
The thing is that netgraph also handles things that are not really netgraph specific (like event listener for scroll zoom)... so this may get confusing too

**Comment by Seanny123** [comment]
Right, so when I mean `netgraph_components` I mean stuff like `value.js`, `slider.js`, `netgraph_item.js` and `netgraph_conn.js`.

**Comment by tcstewar** [comment]
> Right, so when I mean netgraph_components I mean stuff like value.js, slider.js, netgraph_item.js and netgraph_conn.js.

Hmm, I wouldn't consider value.js or slider.js as part of the netgraph.  The NetGraph is meant to be just that thing in the background that has boxes and arrows (i.e. a graph of the network, in the sense of nodes and connections being a graph).  The NetGraph is used to generate the sliders and value plots and other Components.

**Comment by tcstewar** [comment]
I could definitely see a ```components``` subdirectory, with value.js, slider.js, slidercontrol.js, xyvalue.js, raster.js, and pointer.js in it....  Not sure about any other reorganizing, though.

**Comment by Seanny123** [comment]
Thanks for clarifying Terry. I'm still getting the hang of all the linguo in this code.

For the `panel_components` folder, I was (not super seriously) thinking of the `sim_control`, `menu` and `ace`. What do you folks think of that?

**Comment by Seanny123** [comment]
I would also like to split up `nengo.js` into `nengo_component.js`, `nengo_datastore` and `nengo_utils`.

**Comment by Seanny123** [comment]
Finally, is there a reason that `action.py` isn't it's own folder and all of the different classes split up into different files? Am I being a bit too harsh with the "one class per file" thing that I saw in the Nengo repository?

**Comment by tcstewar** [comment]
> I would also like to split up nengo.js into nengo_component.js, nengo_datastore and nengo_utils

I like the splitting up, but I'd do ```component.js```, ```datastore.js```, and ```nengo.js```

**Comment by tcstewar** [comment]
> Finally, is there a reason that action.py isn't it's own folder and all of the different classes split up into different files? It seems like a logical thing to do, since action.py is totally unlike any of the other components. Am I being a bit too harsh with the "one class per file" thing that I saw in the Nengo repository?

I'd say that's too harsh on the "one class per file" thing, since those are all pretty small classes.

That said, it should probably be moved up to ```nengo_gui``` rather than being in ```nengo_gui/components```, since it's not a Component.

**Comment by tcstewar** [comment]
> For the panel_components folder, I was (not super seriously) thinking of the sim_control, menu and ace. What do you folks think of that?

Possibly...  my worry is that it introduces a new concept ("Panel")....  And I don't expect there to be more than those three so it seems a bit odd to have a whole new category for it.  So I think the clutter will be vastly reduced by getting the Components into their own directory, which makes me less inclined to make lots of little sub-folders with only a few things in them....

**Comment by Seanny123** [comment]
So for the `component` folder structure (where we're going to put `slider` and that stuff), does that mean the final folder structure will be `nengo_gui/component/component` (because you said you didn't like `netgraph_components`? Were you implying something else?

**Comment by tcstewar** [comment]
> So for the component folder structure (where we're going to put slider and that stuff), does that mean the final folder structure will be nengo_gui/component/component (because you said you didn't like netgraph_components? Were you implying something else?

I'm not sure I understand....  Why take the files out of ```static```?  I was just envisioning something like this:

```python
static/component.js
static/datastore.js
static/nengo.js
static/component/slider.js
static/component/value.js
...
```

I could maybe see ```static/component/component.js``` instead of ```static/component.js```, if that's what you meant -- I'm not sure which is clearer but my first instinct is ```static/component.js```.

**Comment by Seanny123** [comment]
Ah, nevermind. I forgot we were talking about the `static` folder in the first place. My attention had strayed to the `components` Python folder.

So to summarize the changes I should make in a pull request are:
- Split up `Nengo.js`
- Make a `static/component` folder

**Comment by tcstewar** [comment]
> Move component.py down to nengo_gui

Possibly, although that one I don't think had come up in the above discussion, and seems rather unrelated to the other two points...  In fact, given that ```component.py``` is already there, that might make an argument for the new ```component.js``` to be in ```static/component/component.js``` rather than ```static/component.js```.

**Comment by Seanny123** [comment]
I think I should get some sleep before I continue this conversation...

When I wrote about moving `component.py` I actually meant `action.py`. But I'm glad that allowed us to clear up the position of `component.js`. (:

**Comment by jgosmann** [comment]
> The thing is that netgraph also handles things that are not really netgraph specific (like event listener for scroll zoom)... so this may get confusing too

Or it might be an indication that some refactoring is in order.

I'm definitely in favor of adding some more organization to those files, but can't comment on what the right organization is right now.

**Comment by Seanny123** [comment]
One more thing, would it be possible to rename `action.py` to `server_action.py` which would give a much better indication as to what functions one might find in the file?

**Comment by tcstewar** [comment]
> One more thing, would it be possible to rename action.py to server_action.py which would give a much better indication as to what functions one might find in the file?

Hmm.. possibly, although I'm not sure that ```server_action``` is the right name....  these strike me as client actions, if anything....  or perhaps ```user_action```?

**Comment by Seanny123** [comment]
+1 for `user_action.py` which indicates that the code in the file is called when the user does an action.
