### ISSUE TITLE
Creating an additional nengo.Network inside the model breaks backend selector

### ISSUE THREAD

**Issue by pabogdan** [nengo/nengo_gui#507]
Minimal example:
```python
import nengo
import numpy as np

model = nengo.Network("Network of networks")
with model:
    net1 = nengo.Network("Subnet")
    with net1:
        input_value = nengo.Node(size_in=1)
        A = nengo.Ensemble(40, 1)
        output_val = nengo.Node(size_in=1)

        nengo.Connection(input_value, A)
        nengo.Connection(A, output_val)

    sine = nengo.Node(output=np.sin)
    nengo.Connection(sine, input_value)
```
The backend selector should have a list containing nengo and nengo_spinnaker as it usually does.
![screenshot 14](https://cloud.githubusercontent.com/assets/1470639/8927597/6dcbb77e-3510-11e5-96e5-c8545008656f.png)

This is how it should look like:
![screenshot 15](https://cloud.githubusercontent.com/assets/1470639/8927663/fab629ee-3510-11e5-844c-ac4cde96904d.png)

**Comment by jgosmann** [comment]
Potentially related to #432.

**Comment by jgosmann** [comment]
I can't reproduce the problem. But you might want to check whether PR #521 solves the problem for you.

**Comment by s72sue** [comment]
I can't reproduce this either.
@pabogdan its been long but do you remember whether were you running the GUI on a virtual environment?

**Comment by s72sue** [comment]
I couldn't reproduce this issue on mac OS and linux. Can someone try on a windows machine ?

**Comment by pabogdan** [comment]
@s72sue  I don't recall running the GUI in a virtual environment, and I'm pretty sure I was running it on windows (not completely sure though). Will check and reply asap

**Comment by tcstewar** [comment]
Any luck replicating this issue?  Or should I close it and assume that it got somehow fixed in the various other changes that have been going on?  :)

**Comment by pabogdan** [comment]
I think we can close it. All seems OK now.
