### ISSUE TITLE
Hitting space bar in modals starts/stops the simulation

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#509]
If you pull up a modal to enter values and hit the space bar, the greyed out background sim runs.  Doesn't seem like expected behaviour.  There might even be modals where ' ' is ok... like when typing in semantic pointers.  Or we may just want to let people type spaces between numbers for multiple dimensions.

**Comment by tcstewar** [comment]
That was supposed to be fixed by #485 

Do any of the other hotkeys still function during that modal?

**Comment by celiasmith** [comment]
Crap, my bad, I was on an older branch...
