### ISSUE TITLE
Javascript refactoring

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#517]
I noticed that the `prototype.reset` function of the many things that inherit from `Component` gets repeated a lot everywhere. Can I eliminate this repetition by adding it as a default in `Component`?

**Comment by tcstewar** [comment]
Possibly, although I don't think there'd be much saved there.  Not every component will have a ```data_store```, so that aspect of the ```reset``` shouldn't be moved into ```Component```.

**Comment by Seanny123** [comment]
Right, I just realised not every graph has state, so in that case I won't make the change.
