### ISSUE TITLE
label on response curves / tuning curve plot axes

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo_gui#536]
just noticed there are no labels, i.e. firing rate and input current / x

**Comment by Seanny123** [comment]
Once again, I would take care of this, but I can't for the life me find where this is defined. I know `modal.js` is where the plots get rendered, but where is tuning curve graphs? @tbekolay you seem to be the one who wrote this code.

**Comment by studywolf** [comment]
it's in ```disposable_js.py``` i believe, you create all the plot info on the server side and then ship it over, if memory serves!

**Comment by Seanny123** [comment]
You're right. That really wasn't obvious. I guess that's one more reason to refactor `netgraph_item.js` to make that more obvious, as reported in #206

**Comment by Seanny123** [comment]
Also, what's the difference between a tuning curve and a response curve?

**Comment by studywolf** [comment]
x axis of response curve is input current, J, and x axis of tuning curve is
the vector space signal x (which is why it only plots for 1D ensembles! :)

**Comment by Seanny123** [comment]
On another note, it appears that none of our plots have labels. Is this good or bad? Should they be toggleable or on hover?

**Comment by Seanny123** [comment]
As discussed in the meeting today, comments in the code, as well as then name associated to the graph should give the user enough of a hint as to the function of the graph, even if they didn't create it. So, even though I'm working on including labels as requested (thanks for catching that bug by the way), it's been decided that other axis labels can be inserted manually by users after extracting photos.
