### ISSUE TITLE
Rename `disposable_js.py`

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#539]
Would it be a good idea to clarify the name of `disposable_js.py` to reflect the function that it serves in collaboration with `modal.js`? I was thinking of something like `modal_response.py`. Does anyone else have other suggestions?

**Comment by Seanny123** [comment]
@tbekolay, in the meeting, you mentioned that you mentioned that `disposable_js.py` should just be made part of `user_action.py`. I agreed with this initially, but now I'm somewhat hesitant to follow this through since `user_action.py` is cohesive and neatly put together. I feel like adding more code to the file would add confusion.

Alternatively, I propose seperating the file. In one, create the Python info-modal organsation, which will eventually be made obsolete by the #206 . In the other file, store the code for creating the various plots and call it `static_plots.py`.

Would this be an acceptable alternative?

**Comment by tbekolay** [comment]
I haven't looked at `user_action.py` lately, but I trust that if you don't want to put stuff there then probably best not to. Renaming to `static_plots.py` sounds fine to me; if the info-modal stuff is eventually going to be made obsolete then I wouldn't bother making a separate file for it (just have it in `static_plots.py` even if it's weird). But either way!
