### ISSUE TITLE
Creating semantic pointer cloud on a spa.Compare network causes error

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#559]
If you try to create a Semantic Pointer Cloud on a spa.Compare network it causes an error, because `pointer.py` can't figure out the input vocabulary, because it has multiple inputs. However, this raises a few other issues. Additionally, it should be possible to get a value plot from it's output.

Firstly, neither SPA related plots should be available for that component, since it's output is a scalar and nothing useful can be shown from either the Cloud or the Plot.

Secondly, this same error will be triggered for `spa.Bind` once it's merged to master. In the `spa.Bind` case, I could fix this bug. In other words, I would recommend allowing a Semantic Pointer Cloud and even setting an override value. What do other people think?

**Comment by tcstewar** [comment]
Wow, that's been broken for a long time.  There's no reason for pointer.py to even look at obj.inputs.  It should do everything on the output, I think.   And you are right that it should ignore scalar outputs.

**Comment by Seanny123** [comment]
> There's no reason for pointer.py to even look at obj.inputs

I think the reason `pointer.py` accesses the inputs is to enable over-writing the value. That's what it says in the git blame. Is it possible to do everything on the output instead? I ask, since you're the one who wrote this code in the first place and I don't totally understand how the value is being over-ridden by `gather-data`. (:

**Comment by tcstewar** [comment]
Yes, it's totally possible to do it on the output, since the output is just a Node which can be used as an input.  However, it'll probably take some tweaking of the strength of the overriding input value.

**Comment by Seanny123** [comment]
[This is how I currently understands it works](https://docs.google.com/drawings/d/16e_0rWObGFP_cVN7vG1FS7hD5fZAZ9K6I1e69QHIvAU/edit?usp=sharing). How do you recommend over-riding the output other than this method?

**Comment by tcstewar** [comment]
That's not how it works.

How it currently works is on the left in the picture below.  I've drawn in the Node and the two Connections that are made in pointer.py::add_nengo_objects()

![image](https://cloud.githubusercontent.com/assets/2380772/10003612/40ea2a7e-607b-11e5-9831-2c07e679f539.png)

That approach only works if there's one natural input and one natural output from a component, and if the component is meant to just represent that value.  So, it basically only works for spa.State and spa.AssociativeMemory.  

The alternative approach is what I drew on the right in the picture.  Just connect to the output.  That should do effectively the same thing.  However, the timing implications will be very different (i.e. the low-pass filters on each connection will mean that the timing dynamics for the version on the right will be different than the version on the left).  This may mean that we need to tweak some of these parameters:
- the ```* 3``` scaling in https://github.com/nengo/nengo_gui/blob/master/nengo_gui/components/pointer.py#L61
- the synaptic filters in
https://github.com/nengo/nengo_gui/blob/master/nengo_gui/components/pointer.py#L36

**Comment by tcstewar** [comment]
Btw, I would say this is pretty low-priority -- we should just do an initial fix so that semantic pointer clouds/plots only work for spa.Modules which have a single default input and a single default output (fixing this crash bug), and then do a separate PR for trying to see if we can make this more flexible approach work.

**Comment by Seanny123** [comment]
This is kind of a priority for me, as it would be really nice to have `spa.Bind` to be able to use the pointer cloud with the tutorial that Su and I are working on.

With that motivation in mind, I played around with the code a bit and I found that as long as I boost up the scaling value, everything (vector magnitude, minimal initial oscillations when setting the value) appears to be fine.

This was the code I was testing with:
```
import nengo
from nengo import spa
import numpy as np

# the dimensions of the vectors used to represent the vocabulary
dimensions = 16

# create model and vocabulary
vocab = spa.Vocabulary(dimensions)
vocab.parse("TRIANGLE + SQUARE")
model = spa.SPA(vocabs=[vocab])

def over_func(t, x):
    v = (vocab.parse("TRIANGLE").v - x) * 10
    return v

def mag_func(t, x):
    return np.linalg.norm(x)

with model:
    override = nengo.Node(over_func, size_in=dimensions, size_out=dimensions)
    mag_check = nengo.Node(mag_func, size_in=dimensions, size_out=1)

    model.A = spa.State(dimensions=dimensions)
    model.B = spa.State(dimensions=dimensions)

    nengo.Connection(model.B.input, mag_check)
    nengo.Connection(model.A.output, model.B.input)
    nengo.Connection(model.A.output, override, synapse=0.01)
    nengo.Connection(override, model.A.output, synapse=0.01)

    model.input = spa.Input(A=lambda t: "SQUARE")
```

Have I made a mistake in my testing somewhere?

**Comment by tcstewar** [comment]
Interesting...  seems reasonable to me.  I'm a little bit worried about the ```* 10``` as that's a bit higher than I've normally used it, so I'd also want to test in a few more scenarios, but it doesn't seem too out of the question.

**Comment by Seanny123** [comment]
A boost of `*4` works as well, I was just doing a binary search. :blush: 

What other scenarios would you like to test it in? Just other networks or is there something in specific?

**Comment by tcstewar** [comment]
different # dimensions, different fixed input values ("SQUARE" in your case -- try 10*SQUARE as well, and 0*SQUARE, for that matter)

**Comment by Seanny123** [comment]
Dimensions don't affect anything, but cranking up the input value to
SQUARE*10 does cause problems. However, fewer problems arise than in the
current replacement methodology. Also, the higher the "gain" value on the
node, the fewer problems are seen. For example, in the new implementation
if I make the "gain" `*5` no effect from SQUARE*10 are seen.

**Comment by tcstewar** [comment]
I'm still a bit uncomfortable with the massive ringing artifacts with the higher gain value.  Are you seeing those?  They show up pretty strongly in the example you posted.

The correct solution is to do this overriding as a full PID controller (at the moment, it's just a P controller), but it's probably fine for now sticking with the original gain value (3).  It seems to be no worse than the original approach, in any case.  

So my recommendation is to change the Connection as I showed in my diagram, as that gets rid of any references to ```obj.inputs```.  That should solve the problem and mean that it works fine for spa.Bind.  If we want to address the accuracy of the pointer override in the future, we should do that as a separate PR that implements a full PID controller (with an intergrator reset when the setpoint changes).

**Comment by Seanny123** [comment]
Didn't notice the ringing artifacts, but I'm sure they exist. Because I'm sleepy, I'm not sure what you mean by changing the connection, but I'm sure when I talk to you tomorrow it will make more sense.

I've got a silly question. Is there anyway that we could just inject a node between the output and whatever the output is connecting to? Or just override the output node so it actually has a function?

**Comment by tcstewar** [comment]
> I've got a silly question. Is there anyway that we could just inject a node between the output and whatever the output is connecting to? Or just override the output node so it actually has a function?

Yup, that's also an option, although it gets tricky because there can be multiple connections, and I generally didn't want the gui stuff to be changing aspects of the model itself -- adding new components seems fine, but rewiring a bunch of stuff seems error-prone to me.

**Comment by tcstewar** [comment]
> Didn't notice the ringing artifacts, but I'm sure they exist.

Ringing artifacts in the example code you posted:

![image](https://cloud.githubusercontent.com/assets/2380772/10010718/416f979e-60bd-11e5-914c-0eb3ba7bf364.png)

**Comment by tcstewar** [comment]
> Because I'm sleepy, I'm not sure what you mean by changing the connection, but I'm sure when I talk to you tomorrow it will make more sense.

Sounds like a plan.  And all I meant was the rewiring that you already did.  I was just saying that it looks like it's stable enough that we shouldn't also be adjusting those gain and synapse parameters, so all we have to do is change that one Connection that you already changed.
