### ISSUE TITLE
Weird connection error and behaviour when modifying Thalamus

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#563]
I'm still investigating how to isolate this example, but I'm going to document how I found it here for now.

Using the code and config file found in [this Gist](https://gist.github.com/Seanny123/8b7b38ec9a7d39c16267). Expand the network called `channel_4_memory` in the Thalamus network.

By toggling line line 17 of the code between:
`'dot(memory, E) --> memory=speech'`
and
`'dot(memory, E) --> memory=speech*vision'`

The connection won't be made due to multiple JavaScript errors. The workaround is to just collapse and re-expand the network.

**Comment by ikajic** [comment]
So, working on your branch, this code from the tutorial has some issues with rendering of connections:
```python
import nengo
import nengo.spa as spa

d = 64
model = spa.SPA()

with model:
    model.visual = spa.State(d)
    model.speech = spa.State(d)
    model.hand = spa.State(d)
    model.phrase = spa.State(d)
    
    model.verb = spa.State(d, feedback=1)
    model.noun = spa.State(d, feedback=1)
    
    actions = spa.Actions(
        'dot(visual, SAY+WRITE) --> verb=visual',
        'dot(visual, HELLO+GOODBYE) --> noun=visual',
        'dot(phrase, SAY*VERB) \
            - dot(visual, HELLO+GOODBYE+SAY+WRITE) \
            --> speech=phrase*~NOUN',
        'dot(phrase, WRITE*VERB) \
            - dot(visual, HELLO+GOODBYE+SAY+WRITE) \
            --> hand=phrase*~NOUN',
    )
    model.bg = spa.BasalGanglia(actions)
    # model.thal = spa.Thalamus(model.bg)
    
    cortical_actions = spa.Actions(
        'phrase = verb*VERB + noun*NOUN'
    )
    
    model.cortical = spa.Cortical(cortical_actions)
    
```

Try uncommenting ```model.thal = spa.Thalamus(model.bg)``` and the previously build connections from `visual` to `bg` and `phrase` to `bg` will disappear.

**Comment by tcstewar** [comment]
#579 seems to resolve @ikajic 's bug, but I'm still seeing the original bug @Seanny123 posted.

**Comment by Seanny123** [comment]
Update: when line 17 is changed to `'dot(memory, E) --> memory=speech*vision'` the thalamus becomes unresponsive to size adjustment and attempts to move it via drag and drop.
