### ISSUE TITLE
Give Value plot access to the legend

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#564]
Here's my plan:
- Legend can be toggled via the plot context menu
- Default labels are just "1, 2, 3... etc"
- Editing labels can be done via modal dialogue and csv
- Unlike SpaSimilarity, no values will be shown as the model runs

My motivation for this is I'm going to be wanting to monitor the input and output of the Basal Ganglia. This is the first step towards that.

**Comment by tcstewar** [comment]
Cool!

> Legend can be toggled via the plot context menu

That should probably also happen to the semantic pointer plot too

> Default labels are just "1, 2, 3... etc"

I'd vote for "0, 1, 2,... etc"

> My motivation for this is I'm going to be wanting to monitor the input and output of the Basal Ganglia. 

There has also been a suggestion to directly have a custom plot for those, like we did in Nengo 1.4.  

Also, note that there's a feature of the ```spa.Actions``` that pretty much never gets used that lets you give actions a label (```greet``` and ```bye``` in this case), which could then be used in such a display:

```python
actions = spa.Actions(
   greet='dot(memory, SOMETHING) --> motor=HELLO',
   bye='dot(memory, NOTHING) --> motor=GOODBYE',
)
```

**Comment by tcstewar** [comment]
I believe this is all already done!  :)
