### ISSUE TITLE
Graphs and menu elements get selected

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#599]
As in this screen shot, menus and graph elements often come up selected, somewhat randomly.  Apparently a Mac Chrome issue. (The grey is blue in the GUI, it's a screen cap colour change)

![untitled](https://cloud.githubusercontent.com/assets/1984851/11095747/845efdfa-8864-11e5-819f-945e264e31eb.png)

**Comment by tbekolay** [comment]
Fixed in #600
