### ISSUE TITLE
Simulators cannot be manully run inside nengo_gui

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#621]
I was just trying to run some code using spaopt in the GUI. Spaopt [needs to create a simulator](https://github.com/nengo/nengo/blob/spaopt-v3/nengo/utils/optimization.py#L45) before the actual model is built and this is disallowed in the GUI.

Not sure what the best way to solve this is ... (also I don't have the time to think about it at the moment, but we should come up with a solution when pushing towards the spaopt integration in Nengo master)

**Comment by tcstewar** [comment]
Gah.  Good question.  I'd say there's two options...

1) just get rid of the check that stops a simulator from being built in the gui

2) add a way to explicitly flag the Simulator as being allowed in nengo_gui.  So something like:

```python
with nengo_gui.allow_simulator:
    sim = nengo.Simulator(model)
```

**Comment by Seanny123** [comment]
I personally vote for the second option, since it's a pretty weird use case.

**Comment by jgosmann** [comment]
Explicitely flagging the simulator as allowed seems to be a good approach to me. It catches errors from accidentally creating a simulator, but still allows to do so if required.

However, nengo should not depend on nengo_gui, but how could this be done without such a dependency?

**Comment by tcstewar** [comment]
> However, nengo should not depend on nengo_gui, but how could this be done without such a dependency?

I think a conditional import would be okay...  still a little ugly though:

```
try:
    import nengo_gui
except ImportError:
    nengo_gui = None

if nengo_gui is not None:
    with nengo_gui.allow_simulator:
        sim = nengo.Simulator(model)
else:
    sim = nengo.Simulator(model)
```

Hmm..  maybe a dummy fallback class (like our ```compat``` module) might work....

**Comment by Seanny123** [comment]
@jgosmann spa-opt doesn't need to create a simulator anymore, right? Now you either use a helper function or the new `nengo_spa` library? Consequently, this issue is far more hypothetical?

**Comment by jgosmann** [comment]
Yes, use `nengo_spa`. It is superior to the old spa-opt in all aspects.

**Comment by Seanny123** [comment]
Should we then close this issue if there's not really a clearly use case for it anymore?

**Comment by jgosmann** [comment]
idk, there might be other situations where it is necessary to run a simulator to obtain some data for the actual model?
I'm fine either way.

**Comment by Seanny123** [comment]
I'll close it until we have further insight as to what that scenario may be. (:
