### ISSUE TITLE
console popup with editor closed

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo_gui#632]
So i've taken to only editing the code outside the browser, since there are some weird save things and all my bindings and plugins etc etc, but that console popup with the error is really handy. It would be nice to have that possible to see even with the editor closed, since it's much nicer with the editor closed if you're not actually editing in the browser. Aside from getting that console error popup. Maybe having the editor window pop open if there's an error (without resizing the rest of things) showing the error and the part in the code where it's been thrown, and then pop closed when it goes away or something.

**Comment by tcstewar** [comment]
With the new non-autohiding console, is this still an issue for you?  :)

**Comment by studywolf** [comment]
right! this is no longer an issue!
