### ISSUE TITLE
Backspace Navigation

### ISSUE THREAD

**Issue by rsimmons1** [nengo/nengo_gui#633]
Hitting backspace and accidentally redirecting the page is a tedious issue. It occurs when the user has last clicked on the netgraph, but then hits backspace to edit their code without realizing that the IDE was not selected. This issue occurs on chrome but not firefox. In general the GUI does not seem friendly to browser navigation versus internal GUI navigation so I think it would be best if backspace as navigation was disabled.

**Comment by Seanny123** [comment]
Resolved via merging #665
