### ISSUE TITLE
Lorenz tutorial Simulation

### ISSUE THREAD

**Issue by rsimmons1** [nengo/nengo_gui#641]
Very randomly I've found that the equations in the lorenz simulation become stable (the lines on the graph stop moving) and the x-y graph shrinks into a point, is this suppose to be possible? I'm not sure how to recreate this issue at the moment.

**Comment by tcstewar** [comment]
We should probably set a seed for this one, as yeah, it'll happen sometimes....

**Comment by tcstewar** [comment]
Fixed by #664
