### ISSUE TITLE
Pressing gear button changes it back to play

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#659]
This is weird. Someone should fix it.

**Comment by jgosmann** [comment]
Doesn't that abort the build process? So it makes somewhat sense ...

**Comment by drasmuss** [comment]
No, the build process continues to run, it just changes the icon (giving the false impression that the build process has been aborted).

**Comment by jgosmann** [comment]
Yeah, someone should fix that then.

**Comment by tcstewar** [comment]
Fixed by #660
