### ISSUE TITLE
Extra node tags generated in netgraph.

### ISSUE THREAD

**Issue by rsimmons1** [nengo/nengo_gui#680]
For every node object in the netgraph, there is also a unseeable and pointless node generated somewhere (currently unable to find) in the html. To check for yourself, run the defauly.py  and in the console type (without quotes) """nodes = $(".node")""" a list should be returned that contains the stim node and the second item is a tiny invisible square. This also occurs for ensemble objects.

**Comment by drasmuss** [comment]
Those are the minimap objects (if you open up the minimap you will see the object it is referring to).
