### ISSUE TITLE
Voltage/Spike Plots

### ISSUE THREAD

**Issue by rsimmons1** [nengo/nengo_gui#692]
If a voltage plot is made of an ensemble that has less than 5 neurons, probe errors occur in the server
```
Traceback (most recent call last):
  File "/home/rees/nengo_gui/nengo_gui/server.py", line 142, in ws_viz_component
    component.update_client(client)
  File "/home/rees/nengo_gui/nengo_gui/components/voltage.py", line 46, in update_client
    data = sim.data.raw[self.probe][:]
KeyError: <Probe at 0x7f4837111990 of 'voltage' of <Neurons of <Ensemble (unlabeled) at 0x7f4836e08090>>[:5]>
```
As well it seems arbitrary that voltage/spike plots only show 5 neurons, I think the user should be able to set the number of neurons showed in the graph.

**Comment by tcstewar** [comment]
This doesn't seem to happen for me on the most recent master version of nengo.  Could you confirm that it still happens for you?

**Comment by Seanny123** [comment]
This bug no longer occurs and as of #739 the feature request mentioned in the OP has been satisfied, so I'm now closing the issue.
