### ISSUE TITLE
self._n_steps = self.signals[self.model.step].copy()

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo_gui#699]
When I run this script 
```python
import nengo

model = nengo.Network()
with model:
    def prt(t):
        print t
        return 0
    stim = nengo.Node(prt )
    a = nengo.Ensemble(n_neurons=50, dimensions=1)
    nengo.Connection(stim, a)
```
i get the following 
```bash
Traceback (most recent call last):
  File "/home/tdewolf/Dropbox/code/nengo_gui/nengo_gui/page.py", line 466, in runner
    self.sim.step()
  File "/home/tdewolf/Dropbox/code/nengo/nengo/simulator.py", line 199, in step
    self._probe()
  File "/home/tdewolf/Dropbox/code/nengo/nengo/simulator.py", line 177, in _probe
    self._probe_step_time()
  File "/home/tdewolf/Dropbox/code/nengo/nengo/simulator.py", line 146, in _probe_step_time
    self._n_steps = self.signals[self.model.step].copy()
TypeError: 'NoneType' object has no attribute '__getitem__'```
when it stops

**Comment by arvoelke** [comment]
I think I've seen this sort of error in Jupyter as well when I forget to rerun a simulation after changing my probes. So it could be a case of `nengo_gui` rebuilding the model but using an old version of the simulator object?

**Comment by studywolf** [comment]
actually i'm just getting this popping up after running any script and then doing something like adding another plot

**Comment by tcstewar** [comment]
Weird...  there should be no Probes at all in the nengo_gui model....

**Comment by tcstewar** [comment]
Hmm, I don't get this error with the current master nengo_gui and current master nengo (on Windows).

**Comment by studywolf** [comment]
ahh eff sorry i switched to master nengo gui but might be using a branch of nengo.

**Comment by studywolf** [comment]
alright double checked it, i still get this with most recent master of nengo_gui and nengo on ubuntu (using chrome) just from running the default opening script and then adding a value plot

**Comment by tcstewar** [comment]
> alright double checked it, i still get this with most recent master of nengo_gui and nengo on ubuntu (using chrome) just from running the default opening script and then adding a value plot

???? Weird....  I don't get this at all.

**Comment by tcstewar** [comment]
Oooo... interestingly, I do get this if I hit the reset button (on the left of the bottom toolbar)!  I'll see if I can track that down....

**Comment by tcstewar** [comment]
The offending commit in nengo for me that triggers this is https://github.com/nengo/nengo/commit/b428223719b337b2fee72c8f7b2b652b0b1aa59f

(if I go do git checkout 780d681, I don't get this error when I reset the sim, but I do get it on git checkout b428223 )

**Comment by tcstewar** [comment]
@studywolf can you confirm the minimal series of steps you go through to cause this error?  For me, I can only get it to happen if I reset the simulation (pressing the button on the bottom-left of the gui)

**Comment by studywolf** [comment]
yup! for me i can just open nengo_gui to the default script / config file,
run it, pause it, and then create a value plot

**Comment by studywolf** [comment]
@tcstewar same for me, that's the commit that causes it

**Comment by tcstewar** [comment]
It looks to me like what's happening is that nengo_gui is closing the Simulator while a step() is still happening.....  tracking things down now....

**Comment by tcstewar** [comment]
@studywolf could you check if the nengo branch "fix-close-during-step" solves the problem for you?

**Comment by tcstewar** [comment]
(Note: I'm not proposing that branch as an actual fix -- it's more of a hack.  If that branch does solve things for you, though, then I think I can tweak nengo_gui a bit so that it never tries to close a simulator while it's in the middle of running a step.)

**Comment by studywolf** [comment]
Will do! Afk atm but will lyk when gtg!

**Comment by studywolf** [comment]
yup that fixed it for me
