### ISSUE TITLE
Sliders don't work on reset

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#711]
As a minimal example, use
```
import nengo

model = nengo.Network()
with model:
    stim = nengo.Node([0])
```
Open a slider and a value plot. Move the slider to a value (e.g. 1) and run the model, the value plots zero.  This also happens after any reset.

**Comment by arvoelke** [comment]
This could be related to #699. @tcstewar mentioned a temporary fix there.

**Comment by tcstewar** [comment]
I can't replicate this with the latest master...  @celiasmith could you check if it's still happening for you?
