### ISSUE TITLE
Using Nengo from virtualenv

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#715]
When starting nengo_gui in a virtualenv (even if if nengo_gui is installed in that virtualenv) it will not use the Nengo version installed in the virtualenv (at least this seems what is happening, not completely sure if I messed up somewhere). Not sure what the best solution is. We can detect the virtualenv and activate it ([example code here](https://github.com/jgosmann/psyrun/blob/master/psyrun/venv.py)), but there might be issues with that.

**Comment by tbekolay** [comment]
This works for me. In a virtualenv, if I add
```python
import nengo_gui
print(nengo_gui.__file__)
```

to the code editor, it prints

```
/home/tbekolay/.virtualenvs/nengo3/lib/python3.5/site-packages/nengo_gui/__init__.py
```

What is your exact environment setup? Are you sure you're not executing nengo_gui in a separate process / shell when you mean to start it in the current shell or a subshell?

**Comment by jgosmann** [comment]
Hm, even my Python imports the wrong nengo.

**Comment by jgosmann** [comment]
Note, that I'm using a virtualenv with system site packages.

**Comment by jgosmann** [comment]
Something's messing up my path and is inserting the system site packages path in front ... :angry:

**Comment by tbekolay** [comment]
I was going to say to look in `sys.path` -- good luck finding what's messing that up ... no idea what could be doing that. `grep -R "sys\.path\." /` I guess!

**Comment by jgosmann** [comment]
Managed to get it working for now by uninstalling the system nengo.
Will have to figure out later what's going on.
