### ISSUE TITLE
Pressing cancel on the config screen clears auto-sync

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#744]
Ever since the auto-sync option was added, every now and then someone would report that the checkbox for "automatically synchronize model with editor" would be cleared, and it was very unclear why.  

I just figured out how to replicate the bug:

Step 1: go to the config menu
Step 2: hit "Cancel"

All of the other options go back to their original value.  The auto-sync option gets cleared.  I'm still not quite sure why, but this at least should help track down the bug.

**Comment by tcstewar** [comment]
Found the bug and fixed it in #745

**Comment by Seanny123** [comment]
Resolved with the merging of #745
