### ISSUE TITLE
Connections not shown in Edge

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo_gui#754]
`nengo.Connections` are not being displayed in [Edge](https://www.microsoft.com/en-us/windows/microsoft-edge#5RKKGH090xcZGILB.97)

**Comment by tcstewar** [comment]
This bug may be becoming more important, as it looks like in certain versions of Windows you cannot change the default browser from Edge....  https://arstechnica.com/gadgets/2017/05/windows-10-s-edge-bing-default/

(But at the very least we should show a warning or something here....)

**Comment by jgosmann** [comment]
Seriously? 😲 [They were sued for similar things in the EU before ...](http://www.bbc.com/news/technology-21684329)

**Comment by tcstewar** [comment]
Ah, looks like it's just versions of Windows that are locked-down to only run things from the app store, so we probably couldn't run Nengo on them anyway.....

**Comment by tcstewar** [comment]
Edge seems to display everything correctly now!
