### ISSUE TITLE
Slider doesn't disappear after the nengo.Node was deleted

### ISSUE THREAD

**Issue by ricardodeazambuja** [nengo/nengo_gui#759]

**Comment by Seanny123** [comment]
This doesn't happen to me on the `master` branch using Linux. What OS and browser are you running? What steps can be used to reproduce the issue?

**Comment by Seanny123** [comment]
I still can't reproduce it using Firefox and Windows, so I'm going to close this issue. However, feel free to re-open it if you find this bug again!
