### ISSUE TITLE
Reset (rewind?) button fails

### ISSUE THREAD

**Issue by ricardodeazambuja** [nengo/nengo_gui#786]
I can't remember in which particular situation, but I had problems when I was working with the NeuroGoose code and the simulation would not reset unless I forced it by reloading the browser page.

The only different thing I did was unchecking the "Automatically synchronize..." inside the Configure Settings.

By the way, the "Configure Settings" changes its name to "Configure Options" when the window opens

**Comment by Seanny123** [comment]
Hey Ricardo,

Although I appreciate you reporting this bug, it's unclear from your report how we could reproduce it or fix it. What do you mean by "would not reset"? What aspects of the simulation repeated themselves?

**Comment by ricardodeazambuja** [comment]
After clicking on the "|<<" button the state of the system was not reset. I really can't remember exactly the details, but I do remember swearing because after the reset the robot would not reset to the starting joint values, etc. It would only reset at the beginning (or if not much time had passed since the forced browser refresh) or when the browser window was forced to refresh. It was like if the states were kept the same.

**Comment by tbekolay** [comment]
I'm guessing that you were connecting to the robot with a `Node`. Was the output emitted from the node a normal function? If so, then there's no way for Nengo to know that the function came from an object and therefore reset the object to its initial state.

We made an object called a `Process` to deal with this, and allow people to make custom objects that Nengo could then reset. They're described in some detail in [this notebook](http://pythonhosted.org/nengo/examples/processes.html). If you post the original model, we could show you how to convert that to a model that uses processes and is therefore resettable.

**Comment by ricardodeazambuja** [comment]
Ok, now I got it: "One advantage to using a process over a simple function is that if we reset our simulator, make_step will be called again and the process state will be restored to the initial state."
I was expecting to kill the python interpreter and start from scratch after the "|<<", but it seems the only way to do this is refreshing the browser (and I think there's already an issue about this lack of a "hard" reset button).
Thanks!
