### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by ricardodeazambuja** [nengo/nengo_gui#792]
This seems to be a little bit random. Sometimes I have this error after working for a while with the same file. I had three np.memmap calls opening files at the top of the script.

It seems like instead of killing the processes, I'm just creating new ones, therefore the files stay open.

I can't simply use the "with" statement, I suppose, because I need to open multiple files.

**Comment by arvoelke** [comment]
A possible work-around is to `import` a separate file, in which you do the `np.memmap` calls and then expose the results. Since Python only imports a file once per process (unless `reload` is used), this means repeated changes to the model (via the editor) won't cause those lines to be repeatedly run.

**Comment by jgosmann** [comment]
I don't see how multiple files prevent you from using the `with` statement ...

**Comment by tbekolay** [comment]
To expand on @jgosmann's comment, you can chain multiple context in a `with` statement, like so:

```python
with open('file1.txt') as f1, open('file2.txt') as f2, open('file3.txt') as f3:
    # do stuff with files
```

Also, if that starts getting too big ugly, you don't have to put the `open` part in the `with` statement.

```python
f1 = open('file1.txt')
f2 = open('file2.txt')
f3 = open('file3.txt')

with f1, f2, f3:
    # do stuff with files
```

**Comment by Seanny123** [comment]
Hey Ricardo,

Do the replies to this issue solve your problem or may we close this issue?

**Comment by ricardodeazambuja** [comment]
Yes, the suggestions solved my problem.
