### ISSUE TITLE
Nengo_GUI freezes periodically

### ISSUE THREAD

**Issue by arnav-gudibande** [nengo/nengo_gui#813]
<img width="756" alt="screen shot 2016-08-05 at 11 20 26 am" src="https://cloud.githubusercontent.com/assets/15108659/17446554/b817fc06-5afe-11e6-9e38-eb5b9b1f7ecb.png">

While running my project on macOS 10.12, nengo complains about an unavailable resource and freezes intermittently during runtime. However, when running on Ubuntu 14.04 LTS, nengo runs the project without any issues.

Is there any way I can get nengo to stop complaining about this temporarily unavailable resource?

PS. I have also had this problem on OS X 10.11, so the beta macOS version is not the culprit

[Source Code for Project](https://github.com/arnav-gudibande/nengopacman)

**Comment by jgosmann** [comment]
Thank you for the bug report.

We have rewritten a major part of the underlying server architecture of nengo_gui. This hasn't been part of an official release yet, but you can download the current development version from GitHub. Try to install it and see if that problem persists. If you're lucky it might already be fixed. If not, it would be very helpful to get the error output that you get with that version.

Also, as macOS 10.12 is still in beta, we haven't tested nengo or nengo_gui on it yet.

**Comment by tcstewar** [comment]
I think I've found the problem, and it looks like it's in both the old and the new server architecture.  

I've got what I think is a fix for this, but it'd be great if you could see whether this works for your case.

There are two ways to grab this fix.  One would be to use ```git``` to grab the latest version of nengo_gui from github (```git clone http://github.com/nengo/nengo```, ```cd nengo```, ```python setup.py develop --user```) and then switch to the branch where I've added a potential fix (```git checkout fix-resource-unavail```).

The other option is to directly edit the version of nengo you currently have installed.  To do this, edit the file ```/anaconda/lib/python2.7/site-packages/nengo_gui/swi.py``` and replace line 722

```
            bytes_sent += self.socket.send(data[bytes_sent:])
```

with

```
            try:
                bytes_sent += self.socket.send(data[bytes_sent:])
            except:
                pass
```

Do either of those work for you?

**Comment by arnav-gudibande** [comment]
Solution #2 works, thanks @tcstewar
