### ISSUE TITLE
Network position freezes using SPA

### ISSUE THREAD

**Issue by studywolf** [nengo/nengo_gui#887]
Getting really weird freezing behaviour where I can't drag networks, something is up! No errors come up in the terminal though...

```
import numpy as np

import nengo
import nengo.spa as spa
from nengo.spa import Vocabulary

# Read in the class mean for numbers from vision network
weights_data = np.load('params.npz')
weights = weights_data['Wc']
means_data = np.load('class_means.npz')
means = np.matrix(1.0 / means_data['means'])
sps = np.multiply(weights.T, means.T)[:10]
sps_labels = [
    'ZER0', 'ONE', 'TWO', 'THREE', 'FOUR',
    'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE']
dimensions = weights.shape[0]

# Create our vocabulary
rng = np.random.RandomState(0)
vocab = Vocabulary(dimensions=dimensions, rng=rng)
for label, sp in zip(sps_labels, sps):
    vocab.add(label, np.array(sp)[0])

model = nengo.Network()
with model:
    weight_gen = spa.State(dimensions, subdimensions=10, label='weights', vocab=vocab)
    model.input = spa.Input(weights_gen='.5 * TWO + .5 * EIGHT')
```

with [class_means](https://github.com/xchoo/spaun2.0/blob/experimental/_spaun/modules/vision/lif_vision/class_means.npz) and [params](https://github.com/xchoo/spaun2.0/blob/experimental/_spaun/modules/vision/lif_vision/params.npz)

**Comment by jgosmann** [comment]
When using SPA modules you have to use `spa.SPA()` as your top level network and assign all SPA modules as attributes to this top level network. (Same issue was reported in #883 and #640).

Note that this limitation will likely be resolved in the new nengo_spa.

**Comment by studywolf** [comment]
huzzah! that fixed it, thanks!
